import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "outline-variant": "#c7c4d8",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#e1e0ff",
        "secondary-container": "#6063ee",
        "primary-container": "#534ad9",
        "on-tertiary-fixed": "#351000",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "secondary": "#4648d4",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed": "#ffdbcc",
        "on-surface-variant": "#464555",
        "on-background": "#191c1e",
        "on-primary-fixed-variant": "#372abf",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#c3c0ff",
        "surface-tint": "#5148d7",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#dbd7ff",
        "surface-container-low": "#f2f4f6",
        "error": "#ba1a1a",
        "primary-fixed": "#e3dfff",
        "on-tertiary": "#ffffff",
        "outline": "#777587",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#7b2f00",
        "background": "#f7f9fb",
        "on-tertiary-container": "#ffd2be",
        "tertiary": "#7e3000",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#07006c",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb695",
        "primary": "#392cc1",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#a44100",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed": "#100069",
        "primary-fixed-light": "#e3dfff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        // ── Type scale ──────────────────────────────────────────────────────
        // Mirror of the CSS variables in globals.css @theme.
        // Edit the CSS variables there; update these values to match.
        "display":  ["5rem",     { lineHeight: "1.1" }],
        "h1":       ["3.5rem",   { lineHeight: "1.1" }],
        "h2":       ["3rem",     { lineHeight: "1.15" }],
        "h3":       ["2.25rem",  { lineHeight: "1.2" }],
        "h4":       ["1.5rem",   { lineHeight: "1.3" }],
        "body-lg":  ["1.125rem", { lineHeight: "1.6" }],
        "body":     ["1rem",     { lineHeight: "1.5" }],
      },
    },
  },
  plugins: [],
};

export default config;
